#undef glAttachShader
#undef glBeginTransformFeedback
#undef glBindBuffer
#undef glBindFramebuffer
#undef glBindProgramPipeline
#undef glBindSamplers
#undef glBindTextures
#undef glBindTransformFeedback
#undef glBindVertexArray
#undef glBlendFunc
#undef glBlitNamedFramebuffer
#undef glBufferStorage
#undef glClear
#undef glClearDepth
#undef glClearTexSubImage
#undef glClipControl
#undef glCompileShader
#undef glCompressedTextureSubImage3D
#undef glCreateBuffers
#undef glCreateFramebuffers
#undef glCreateProgram
#undef glCreateProgramPipelines
#undef glCreateSamplers
#undef glCreateShader
#undef glCreateTextures
#undef glCreateTransformFeedbacks
#undef glCreateVertexArrays
#undef glDebugMessageCallback
#undef glDeleteBuffers
#undef glDeleteFramebuffers
#undef glDeleteProgram
#undef glDeleteProgramPipelines
#undef glDeleteSamplers
#undef glDeleteShader
#undef glDeleteTextures
#undef glDeleteTransformFeedbacks
#undef glDepthFunc
#undef glDepthRange
#undef glDetachShader
#undef glDisable
#undef glDrawArraysInstanced
#undef glEnable
#undef glEndTransformFeedback
#undef glFinish
#undef glFrontFace
#undef glGenBuffers
#undef glGenerateTextureMipmap
#undef glGenTextures
#undef glGetCompressedTextureSubImage
#undef glGetIntegerv
#undef glGetProgramInfoLog
#undef glGetProgramiv
#undef glGetShaderInfoLog
#undef glGetShaderiv
#undef glGetStringi
#undef glGetTextureLevelParameteriv
#undef glGetTextureSubImage
#undef glLinkProgram
#undef glMapBufferRange
#undef glMapNamedBufferRange
#undef glMultiDrawElementsIndirect
#undef glNamedBufferStorage
#undef glNamedFramebufferDrawBuffer
#undef glNamedFramebufferDrawBuffers
#undef glNamedFramebufferReadBuffer
#undef glNamedFramebufferTextureLayer
#undef glProgramParameteri
#undef glProgramUniform1fv
#undef glProgramUniform1iv
#undef glProgramUniform1uiv
#undef glProgramUniform2fv
#undef glProgramUniform3fv
#undef glProgramUniform4fv
#undef glSamplerParameteri
#undef glScissor
#undef glShaderSource
#undef glTextureBufferRange
#undef glTextureStorage3D
#undef glTextureStorage3DMultisample
#undef glTextureSubImage3D
#undef glTextureView
#undef glTransformFeedbackBufferRange
#undef glTransformFeedbackVaryings
#undef glUseProgramStages
#undef glViewport
